spring:
  application:
    name: deal
  datasource:
    url: jdbc:postgresql://localhost:5432/dealDB
    username: student
    password: chocolatefrog
  liquibase:
    change-log: classpath:db/liquibase/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8082
